Разметка первой страницы
htmlacademy-adaptive/129688-pink-22 pull request #2
Opened 2021-03-27 11:43 UTC by dryworts

2021-03-28 19:11 UTC, PavelNyukalo requested changes
Так же валидацию не проходит
![image](https://user-images.githubusercontent.com/52506235/112764679-31e0c000-9023-11eb-9fe7-a8f05b356b96.png)

2021-03-28 19:11 UTC, PavelNyukalo commented on source/index.html
> +          </table>
Таблицу надо всю сверстать, по [ТЗ ](https://up.htmlacademy.ru/adaptive/22/project/pink#pink-4-6)у нас есть требование

2021-03-28 19:11 UTC, PavelNyukalo commented on source/index.html
> +          </p>
Так же с именованием, как для предыдущего слайдера

2021-03-28 19:11 UTC, PavelNyukalo commented on source/index.html
> +        <h3 class="visually-hidden">Контакты</h3>
Для секций идет заголовок второго уровня, а тут - третьего, поправь

2021-03-28 19:11 UTC, PavelNyukalo commented on source/index.html
> +      <section class="map">
Секции с картой тоже давай заголовок дадим

2021-03-28 19:11 UTC, PavelNyukalo commented on source/index.html
> +          </ul>
Тут пару ошибок.
1. Так же именование
2. Для списка задается класс элемента `social__list`, значит родительским блоком для него должен быть элемент с классом `social`, но его нет. `<div class="page-footer__social">` является элементом блока `page-footer`. Чтобы это исправить нам надо примиксовать блок `social` и получится:
```html
<div class="page-footer__social social">
  <ul class="social__list">
.....
</div>
```

2021-03-28 19:11 UTC, PavelNyukalo commented on source/index.html
> +        </div>
Здесь аналогично.
Если, что в демке было это 
![image](https://user-images.githubusercontent.com/52506235/112764622-e0383580-9022-11eb-89b2-d8e14b643568.png)

2021-03-28 19:11 UTC, PavelNyukalo commented on source/index.html
> +            <img class="feature__images__item" src="#" alt="фильтр с надписью Всем привет">
Ошибки по методологии так же в именовании

2021-03-29 03:29 UTC, dryworts commented on source/index.html
> +            <li class="main-nav__list__item"><a href="#">HTML Academy</a></li>
понял, исправил

2021-03-29 03:31 UTC, dryworts commented on source/index.html
> +        <p class="system-icons__description">Доступно для iPhone, iPad, Android,<br>Windows Phone, OS X, Windows 8</p>
ок, исправил

2021-03-29 03:36 UTC, dryworts commented on source/index.html
> +          <button class="look-differently__button">Скачать приложение</button>
ну, да так логично. Я еще не вижу картины в целом  и это первая БЭМ разметка. Но кажется я начинаю понимать

2021-03-29 04:36 UTC, dryworts commented on source/index.html
> +            </li>
Хорошо, пусть будет h3. Но я думаю, что это просто текст.  Именование поправил.

2021-03-29 04:50 UTC, dryworts commented on source/index.html
> +          <div class="features__slider">
вынес, поправил БЭМ

2021-03-29 05:21 UTC, dryworts commented on source/index.html
> +              </li>
Сложно одновременно думать про семантику и БЭМ.  Вижу этот блок по-другому, по-крайней мере пока.  ОК, переделаю.

2021-03-29 06:06 UTC, dryworts commented on source/index.html
> +                <button class="slider-controls-button__current" type="button" aria-label="Первый слайд"></button>
поправил

2021-03-29 12:02 UTC, dryworts commented on source/index.html
> +          </p>
угу, использовал такой же

2021-03-29 12:04 UTC, dryworts commented on source/index.html
> +        <h3 class="visually-hidden">Контакты</h3>
готово

2021-03-29 12:05 UTC, dryworts commented on source/index.html
> +      <section class="map">
ок

2021-03-29 12:23 UTC, dryworts commented on source/index.html
> +        </div>
кажется я начал понимать )

2021-03-29 12:32 UTC, dryworts commented on source/index.html
> +            <img class="feature__images__item" src="#" alt="фильтр с надписью Всем привет">
поупражнялся. Наверное, тут главное понять зачем все это ))) но я верю, что надо )

2021-03-29 17:35 UTC, PavelNyukalo requested changes

2021-03-29 17:35 UTC, PavelNyukalo commented on source/index.html
> +            <li class="main-nav__item main-nav__list__item--active"><a>Главная</a></li>
Для активного пункта ошибка в именовании сохранилась

2021-03-29 17:35 UTC, PavelNyukalo commented on source/index.html
> +            </li>
Здесь тоже смотри еще осталась ошибка именования. В БЭМ дереве иерархия элементов плоская, т.е. вложенность например
```html
<ul class="list">
  <li class="list__item">
    <a class="list__link">
      <img class="list__image">
    </a>
  <li>
</ul>
``` 

по БЭМу будет выглядеть как
```html
list
  list__item
  list__link
  list__image
```

то есть один уровень вложенности - элементы внутри блока.
Конкретно в этой ситуации у нас будет
```html
<ul class="features__list">
  <li class="features__item">
    <h3 class="features__title">
    </h3>
  </li>
</ul>
```

2021-03-29 17:35 UTC, PavelNyukalo commented on source/index.html
> +        <div class="features__slider">
Тут у нас уже блок с отзывами, а сейчас по БЭМ выглядит будто это элемент блока `features`, поэтому тут будет у секции класс `reviews` например, а у слайдера `reviews__slider`

2021-03-29 17:35 UTC, PavelNyukalo commented on source/index.html
> +        <div class="look-diffently__wrapper">
Здесь кстати недопечатал название у `look-diffently__wrapper` - diffently, а блок differently

2021-03-29 17:35 UTC, PavelNyukalo commented on source/index.html
> +            </div><!--конец блока коментов-->
Ну и кстати можно в целом тут поменять слово `slider` у цитат на `reviews`. Т.е. `reviews__list`, `reviews__item` и т.д. А класс "слайдер" оставить чисто у кнопок слайдера непосредственно

2021-03-29 17:35 UTC, PavelNyukalo commented on source/index.html
> +        <div class="page-footer__social">
Тут не добавил блок `social`, а вот копирайт добавил

2021-03-30 03:38 UTC, dryworts commented on source/index.html
> +            </li>
тут понял, хочу подчеркнуть принадлежность элементов li к ul, сделал  features-list__item. Ничему не противоречит.

2021-03-30 03:45 UTC, dryworts commented on source/index.html
> +        <div class="features__slider">
угу. Ну вообще так и было, не было секции и все это входило в большой блок features. Потом появилась еще одна секция, конечно же я не стал заморачиваться с названиями. Это уже больше лингвистика какая-то.  Исправляю.

2021-03-30 03:50 UTC, dryworts commented on source/index.html
> +        <div class="look-diffently__wrapper">
ага, очепятка, спасибо

2021-03-30 03:51 UTC, dryworts commented on source/index.html
> +            </div><!--конец блока коментов-->
так сразу и сделал )

2021-03-30 04:14 UTC, dryworts commented on source/index.html
> +        <div class="page-footer__social">
ну меня понесло и я написал длинный коммент, потом опомнился, стер. Короче этот БЭМ пока больше выводит меня из себя, чем помогает. Надеюсь будет помогать.

2021-03-30 12:43 UTC, PavelNyukalo approved these changes

2021-03-30 12:43 UTC, merged