Пересоздал form.html
htmlacademy-adaptive/129688-pink-22 pull request #4
Opened 2021-03-31 14:25 UTC by dryworts

2021-04-01 13:49 UTC, PavelNyukalo requested changes
Так же есть предложение блок с главным заголовком сделать общим для всех трех страниц, а уже наполнение менять. Просто сейчас по сути блок с главной страницы
```html
<section class="look-differently">
  <div class="look-differently__wrapper">
    <h1 class="look-differently__header">Взгляните на жизнь иначе!</h1>
  </div>
  ...другие элементы
</section>
```
и блок с заголовком с этой страницы
```html
<section class="competition">
  <div class="competition__wrapper">
    <h1 class="competition__header">Конкурс на самое безбашенное путешествие с Пинк</h1>
  </div>
</section>
```
выглядят одинаково (за исключением дополнительного контента на главной), но по БЭМ-нотации это два разных блока и придется делать два файла, а стили дублировать.
Поэтому предлагаю этот промо-блок сделать единым для всех, с фоновой картинкой и т.д, а вот уже доп. контент по мере надобности добавлять другими блоками (как например `system-icons`)
![image](https://user-images.githubusercontent.com/52506235/113301199-30abdd80-9318-11eb-96b2-ccbe40b8690d.png)
![image](https://user-images.githubusercontent.com/52506235/113301224-3a354580-9318-11eb-92ec-9ae607eff36d.png)

2021-04-01 13:49 UTC, PavelNyukalo commented on source/form.html
>                  </li>
Может назвать этот блок не `list-item`, а например - `checkbox`? Если вырвать из контекста, checkbox более понятно звучит, чем просто list-item. И можно тогда именование поправить, как-нибудь так
```
checkbox
  checkbox__label
  checkbox__input
  checkbox__icon
``` 
А вот текст подписи (видел чака норриса и др.) можно в `span` не оборачивать, они и так будут текстом `label`

2021-04-01 13:49 UTC, PavelNyukalo commented on source/form.html
>              </div>
Думаю, это можно сделать тоже `fieldset`, тоже ведь группа полей, а рамку уберем через модификатор

2021-04-01 13:49 UTC, PavelNyukalo commented on source/form.html
> +    </section>
1. Текста совпадают, поправь
2. Думаю, можно не создавать два разных блока - `modal-error` и `modal-success`, а оставить и стилизовать чисто блок `modal`. Просто оба попапа выглядят одинаково на макете, и задавать одинаковые стили для двух блоков нет смысла

2021-04-02 05:35 UTC, dryworts commented on source/form.html
>          <h2 class="visually-hidden"></h2>
Насчет общего вроде понял, переделал как понял )

2021-04-02 05:58 UTC, dryworts commented on source/form.html
>                  </li>
один из элементов у меня называется list-item__checkbox  и все понятно, не хочу checkbox__checkbox или другие варианты. Мысль я понял. Брр ... не хочу скатываться в фонетику, но  item - элемент, элемент чего? правильно - списка. Что такое checkbox? поле ввода, type checkbox - флажок, да и то все это в форме.  Поэтому что понятно? понятно что в форме. Но постойте какой форме? А так - бац! - элемент списка и точка.

2021-04-02 06:07 UTC, dryworts commented on source/form.html
>              </div>
ок

2021-04-02 06:22 UTC, dryworts commented on source/form.html
> +    </section>
Упс, не заменил ))) Два разных оставим. Тут тоже можно нафантазировать, что пришел глав ред и теперь поменяются визуальные эффекты, цвета кнопок, шрифтов, нафигачим одну модалку розовой, а другую готичной. ) А если без шуток, то очевидно что модалку с ошибками нужно допилить красным цветом и на js должны быть эффекты отличные от блока успеха. Тексты поправил. Спасибо за все замечания.

2021-04-02 10:01 UTC, PavelNyukalo approved these changes

2021-04-02 10:01 UTC, merged