Создает файл catalog.html
htmlacademy-adaptive/129688-pink-22 pull request #5
Opened 2021-04-02 11:43 UTC by dryworts

2021-04-02 12:34 UTC, PavelNyukalo requested changes

2021-04-02 12:34 UTC, PavelNyukalo commented on source/catalog.html
> +        <div class="photo-of-day">
Класс совпадает с классом на 36 строке, да и в принципе тут можно `div` это не делать, картинка у нас растягивается на всю ширину `section`

2021-04-02 12:34 UTC, PavelNyukalo commented on source/catalog.html
> +        <div class="photo-of-day__wrapper">
Тут этот `div` тоже можно убрать, `blockquote` блочный тег, можно будет стилизовать его

2021-04-02 12:34 UTC, PavelNyukalo commented on source/catalog.html
> +             <cite class="day-block__name">Анна<span class="user-block__time">(5 минут назад)</span></cite>
`user-block__time` элемент не объявленного блока, блока `user-block` у нас нет

2021-04-02 12:34 UTC, PavelNyukalo commented on source/catalog.html
> +              <p class="day-block__like"><span class="user-block__icon"></span>нравится:<span class="user-block__count">215</span></p>
Тут так же с `user-block`

2021-04-02 16:01 UTC, dryworts commented on source/catalog.html
> +        <div class="photo-of-day">
ок, дошло

2021-04-02 16:04 UTC, dryworts commented on source/catalog.html
> +             <cite class="day-block__name">Анна<span class="user-block__time">(5 минут назад)</span></cite>
согласен, исправил

2021-04-02 16:08 UTC, dryworts commented on source/catalog.html
> +              <p class="day-block__like"><span class="user-block__icon"></span>нравится:<span class="user-block__count">215</span></p>
этот блок сначала был как и все, а потом уже оказался отдельным от всего списка, невнимательность и спешка делают свое )

2021-04-03 09:21 UTC, PavelNyukalo approved these changes

2021-04-03 09:22 UTC, merged