Module 3.index.html
htmlacademy-adaptive/129688-pink-22 pull request #6
Opened 2021-04-09 17:32 UTC by dryworts

2021-04-11 18:06 UTC, PavelNyukalo requested changes
Так же поправь ошибки `npm test` чтобы можно было смерджить PR, и по заданию необходимо *__всем__* БЭМ-блокам создать свой файл
![image](https://user-images.githubusercontent.com/52506235/114315906-894e5800-9b1a-11eb-80ed-f7644ce09a06.png)
 т.е. и для `copyright`, и для `slider-controls` и т.д, даже если они пока пустые будут, можешь заглушки делать в виде 
```css
.copyright {

}
```
они при прохождении тестов не выбрасывают ошибки и не влияют на мердж PR

2021-04-12 04:06 UTC, dryworts commented on source/less/global/fonts.less
> +  font-style: light;
спасибо.

2021-04-12 06:36 UTC, dryworts commented on source/less/blocks/features.less
> +  font-family: Open Sans;
хорошо

2021-04-12 06:41 UTC, dryworts commented on source/less/global/base.less
> +  width: 320px;
понятно, хорошо.

2021-04-12 06:50 UTC, dryworts commented on source/less/global/base.less
> +  width: 320px;
Хотя теперь верстать вообще не удобно )

2021-04-12 08:34 UTC, dryworts commented on source/less/blocks/reviews.less
> +}
я пока оставлю для определенных блоков свои названия и не буду добавлять им класс visually-hidden, чую может понадобиться использовать другие свойства, например именно display: none. Пока оставлю.

2021-04-12 08:35 UTC, dryworts commented on source/less/blocks/prices.less
> +}
угу.

2021-04-12 10:09 UTC, PavelNyukalo requested changes

2021-04-12 10:09 UTC, PavelNyukalo commented on source/less/style.less
> +@import "blocks/social-list.less";
Если пройтись по `index.html`, то нет файлов для блоков:
- `page`
- `header-index`
- `features-list` (он в `features.less`)
- `hidden-cell` (124 строка в `html`)
- `copyright`

и `page-main` не подключен

2021-04-12 11:33 UTC, dryworts commented on source/form.html
> +              <p class="form__content">Поделитесь своей историей и получите шанс выиграть ценный приз — 1000 миль на вашу бонусную карту!</p><p class="form__content--hidden">Пожалуйста, заполните фор
понял.

2021-04-12 11:35 UTC, dryworts commented on source/index.html
> +    <header class="page-header header-index")>
да! обычный смайлик )

2021-04-12 11:39 UTC, dryworts commented on source/less/blocks/features.less
> +}
ага, пропустил.

2021-04-12 12:09 UTC, dryworts commented on source/less/style.less
> +@import "blocks/social-list.less";
теперь он .prices__hidden-cell , все поправил

2021-04-12 12:10 UTC, dryworts commented on source/less/style.less
> +@import "blocks/social-list.less";
npm test вообще злой, понапридумывали )

2021-04-12 12:42 UTC, PavelNyukalo approved these changes

2021-04-12 12:42 UTC, merged