form.html. Module3-task2.
htmlacademy-adaptive/129688-pink-22 pull request #7
Opened 2021-04-13 09:38 UTC by dryworts

2021-04-13 09:57 UTC, PavelNyukalo requested changes

2021-04-13 09:57 UTC, PavelNyukalo commented on source/form.html
> +          <p class="system-icons__description">Доступно для iPhone, iPad, Android,<br>Windows Phone, OS X, Windows 8</p>
Тут смотри наполнение с индексе вставил, с иконками приложений и тд

2021-04-13 09:57 UTC, PavelNyukalo commented on source/less/blocks/form.less
> +  font-family: "Open Sans", "Arial", sans-serif;
`inherit`, как обсуждали

2021-04-14 03:51 UTC, dryworts commented on source/form.html
> +          <p class="system-icons__description">Доступно для iPhone, iPad, Android,<br>Windows Phone, OS X, Windows 8</p>
упс, да невнимательно

2021-04-14 03:52 UTC, dryworts commented on source/less/blocks/form.less
> +  font-family: "Open Sans", "Arial", sans-serif;
ок, заменил

2021-04-14 04:50 UTC, PavelNyukalo approved these changes

2021-04-14 04:50 UTC, merged