catalog.html. module3-task3
htmlacademy-adaptive/129688-pink-22 pull request #8
Opened 2021-04-14 17:43 UTC by dryworts

2021-04-15 10:05 UTC, PavelNyukalo requested changes

2021-04-15 10:05 UTC, PavelNyukalo commented on source/less/style.less
> +@import "blocks/color-tool.less";
Не подключил блоки `header-catalog` и `brightness-tool`

2021-04-16 16:06 UTC, dryworts commented on source/less/style.less
> +@import "blocks/color-tool.less";
угу, в начале и в конце. Исправляю.

2021-04-16 16:12 UTC, PavelNyukalo approved these changes

2021-04-16 16:13 UTC, merged