module4-task1. Домашка. Ужас.
htmlacademy-adaptive/129688-pink-22 pull request #9
Opened 2021-04-20 12:34 UTC by dryworts

2021-04-26 10:54 UTC, PavelNyukalo requested changes
Так же поправь ошибки `npm test`

2021-04-26 10:54 UTC, PavelNyukalo commented on source/less/blocks/address.less
> +  }
Для медиавыражений нет смысла писать все те свойства, которые были прописаны для мобильной версии - они все равно подтянуться. В медиа необходимо писать только те свойства, которые меняются. Если и на мобильной, и на десктопе применяется например `display: flex`, то прописывать этого же свойство для других медиа уже не надо.

2021-04-26 10:54 UTC, PavelNyukalo commented on source/less/blocks/contact-information.less
> +}
Вот как раз как описал выше предлагаю сделать класс `.container`, ему прописать вот эти стили повторяющиеся
```css
  width: 320px;
  margin: 0 auto;
  padding: 0 20px;
```
и потом просто миксовать в html

2021-04-26 10:54 UTC, PavelNyukalo commented on source/less/blocks/contact-information.less
> +  }
В этом файле не может быть стилей для `address`

2021-04-26 10:54 UTC, PavelNyukalo commented on source/less/blocks/system-icons.less
> +}
Пройдись в целом по всем файлам и удали дублирующиеся свойства для медиа выражения, если на планшетной версии ширина стала 300рх, на десктопной нет смысла ее прописывать снова - она так и останется 300

2021-04-27 06:49 UTC, dryworts commented on source/index.html
> +                <img class="features-list__images-item" src="img/mobile-smile-mobile.png" height="320" width="157" alt="фильтр с надписью Всем привет">
Исправил, спасибо.

2021-04-27 07:19 UTC, dryworts commented on source/index.html
> +        <div class="page-header__wrapper"> <!--ВНИМАНИЕ ЭТО ОПЯТЬ ЦЕНТРОВЩИК-->
попробовал, мысль здравая, в моем первом проекте я так и делал. Применил и все посыпалось. Я пока не хочу тратить много времени на перфекционизм. Завел класс positioner,  на других страницах применю, если останется очень много времени применю и на Index.

2021-04-27 07:25 UTC, dryworts commented on source/index.html
> +          <div class="features__wrapper">
мне так легче думать пока, я так понимаю это вообще не главная проблема )

2021-04-27 09:38 UTC, dryworts commented on source/index.html
> +    </header>
ага, постарался, даже все переверстал. Пол-дня убил. (

2021-04-27 09:59 UTC, dryworts commented on source/index.html
> +          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1998.6037861610246!2d30.3230474!3d59.9387165!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca145cc1%3A0x42b32648d8238007!2z0J
ага, спасибо я взял часть код-сброса Меера и добавил как ты и говорил 100% width, сработало. Спасибо.

2021-04-27 10:04 UTC, dryworts commented on source/less/blocks/address.less
> +}
угу, ок.

2021-04-27 10:10 UTC, dryworts commented on source/less/blocks/address.less
> +  }
а по-большому, какая разница если мне так удобнее? Мне не нравиться подход mobile-first. Я сначала беру блоки десктопной версии и спускаюсь вниз. Этот макет создан явно для того, чтобы мозг поднапрячь. Если идти от мобильной версии, то вообще с ума сойдешь.  Но в целом совет понял, спасибо.

2021-04-27 10:11 UTC, dryworts commented on source/less/blocks/contact-information.less
> +}
так и сделаю, на второй и третьей странице. Я уже много стилей навесил на них и мозг кипит.  Спасибо.

2021-04-27 10:12 UTC, dryworts commented on source/less/blocks/contact-information.less
> +  }
Упс, ок.

2021-04-27 10:49 UTC, dryworts commented on source/less/blocks/contact-information.less
> +  }
еще пару часов, чтоб понять почему при переносе в другой файл все ломается

2021-04-27 10:52 UTC, dryworts commented on source/less/blocks/system-icons.less
> +}
Это из-за того что я верстал от исходя из десктопной версии.

2021-04-28 05:18 UTC, PavelNyukalo requested changes

2021-04-28 05:18 UTC, PavelNyukalo commented on source/less/blocks/look-differently.less
> +  background-image: url("/img/hand-mobile.png");
На мобилке рука все еще не грузится
![image](https://user-images.githubusercontent.com/52506235/116349862-64403180-a80a-11eb-9942-5b6a7aa70958.png)

2021-04-28 05:18 UTC, PavelNyukalo commented on source/less/blocks/effect-description.less
> +    background-image: url("/img/clock-tablet.png");
И часики
![image](https://user-images.githubusercontent.com/52506235/116349943-83d75a00-a80a-11eb-9d92-507fdd7786d7.png)

2021-04-28 16:35 UTC, dryworts commented on source/less/blocks/look-differently.less
> +  background-image: url("/img/hand-mobile.png");
точно, опять ..

2021-04-28 16:36 UTC, dryworts commented on source/less/blocks/effect-description.less
> +    background-image: url("/img/clock-tablet.png");
Это приложение перевернуло мой мир! )))

2021-04-29 16:19 UTC, PavelNyukalo approved these changes

2021-04-29 16:19 UTC, merged